# Generated by Django 3.2.3 on 2024-05-12 04:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#00FF00', image_field=None, max_length=18, samples=None, unique=True, verbose_name='Цветовой код'),
        ),
    ]
